# Generated by Django 3.2.14 on 2022-08-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpName', models.CharField(max_length=30)),
                ('EmpID', models.IntegerField()),
                ('Designation', models.CharField(max_length=40)),
                ('SalaryPackage', models.IntegerField()),
                ('Department', models.CharField(max_length=40)),
                ('Experience', models.IntegerField()),
            ],
        ),
    ]
